const fs = require('fs');
const path = require('path');

const fsController = {
  config: (req, res, next) => {
    const {
      sourceType,
      sourceID,
      sourcePassword,
      destinationType,
      destID,
      destPassword,
      destAccessId
    } = req.body;

    //WILL NEED AWS-SDK AND FLUSH OUT THE LOGIC HERE.
    let content = `[aws]
type = ${sourceType}
provider = AWS
access_key_id = ${sourceID}
secret_access_key = ${sourcePassword}
region = us-east-1`; //THIS WILL BE DYNAMICALLY GENERATED BY US. SAME WITH PROVIDER.

    content += `\n
[cloudflare]
type = s3
provider = ${destinationType}
access_key_id = ${destID}
secret_access_key = ${destPassword}
region = auto
endpoint = https://${destAccessId}.r2.cloudflarestorage.com/`;

    fs.writeFileSync(path.resolve(__dirname, '../../rclone.conf'), content);
    return next();
  }
};

module.exports = fsController;
