name: Delete Build Folder If Exists

on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      - build

jobs:
  delete_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Delete build folder
        run: rm -rf build/