name: Delete Branch (on closed PR)
on: 
  pull_request:
    branches:
      - dev
    types: [closed]
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          if [ "${{ github.event.pull_request.title }}" == "stretch" ]; then
            echo "PR title is 'stretch', skipping branch deletion"
            exit 1
          fi
      - name: Delete Branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 