name: Docker Image CI

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build Docker Image
        run: docker build -t cloudshiftdev/app .

      - name: Push Docker Image
        run: docker push cloudshiftdev/app