#Only whitelisted files should pass. Otherwise, delete the extra files.
name: Staging Whitelisted Files/Folders Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  delete_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete files
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name "server" ! -name "build" ! -name "LICENSE" ! -name "package.json" ! -name ".github" ! -name "package-lock.json" ! -name "README.md" -exec rm -rf {} +
          git add .
          git commit -m "Deleted all non-whitelisted files/folders."
          git push